"""Small dialog primitives for the LLM resolver.

The deterministic resolver and the LLM rewrite layer (PR #33) both
pick *once* from a single top-k shortlist. That's the right default
for batch / scripted use, but it falls over when the query is
genuinely ambiguous — "the conference room" with two equally
plausible matches gets a coin flip rather than a "did you mean A or
B?".

This module adds the minimum vocabulary needed to surface that
ambiguity without committing to a full multi-turn dialog framework:

* :class:`ClarificationQuestion` — the resolver's "I need help"
  output. Carries a human-readable question and the candidates that
  triggered it.
* :class:`ClarificationAnswer` — the caller's reply. Either a
  ``chosen_id`` (an explicit pick from the surfaced candidate ids —
  always re-validated against the deterministic pool, so the safety
  property "no invented node ids" still holds) or a ``free_text``
  hint that the next resolve call appends to its query.
* :class:`AmbiguousGoalError` — raise this when the caller has
  asked for strict mode (``raise_on_ambiguous=True``) and the
  resolver can't pick confidently.

These are intentionally small, frozen, and JSON-friendly so they
can be passed through queues / RPCs / argparse without extra
plumbing. (They aren't hashable because :class:`GoalCandidate`
isn't — a future change could make both frozen and hashable, but
the current dialog flows don't need it.) The richer "session
state across multiple turns" or "mid-traversal rewrite" work
belongs in a later PR; this one just adds the primitive that makes
the rest of that work expressible.
"""

from __future__ import annotations

from dataclasses import dataclass, field

from semantic_toponav.query.resolve import GoalCandidate


@dataclass(frozen=True)
class ClarificationQuestion:
    """A resolver-emitted "I need help" turn.

    Attributes
    ----------
    question:
        Free-text question to show the user. Either generated by the
        resolver itself ("which one did you mean: …?") or extracted
        from the LLM's ``Clarify:`` reply.
    candidates:
        The candidate set that triggered the question, in
        deterministic-score order. The caller's next
        :class:`ClarificationAnswer.chosen_id` must reference one of
        these node ids.
    """

    question: str
    candidates: tuple[GoalCandidate, ...]


@dataclass(frozen=True)
class ClarificationAnswer:
    """A user reply to a previous :class:`ClarificationQuestion`.

    Exactly one of ``chosen_id`` / ``free_text`` is the actionable
    field; the other is informational. ``chosen_id`` is checked
    against the next resolve call's candidate pool — out-of-pool ids
    are silently dropped (the resolver falls back to its own ranking
    rather than blindly trusting an external string).

    Attributes
    ----------
    chosen_id:
        Node id the caller picked from the previous question's
        candidates. ``None`` when the caller didn't (or couldn't)
        pick one explicitly.
    free_text:
        Extra textual hint the resolver appends to the original
        query before re-running. Useful when the caller can't point
        at a specific candidate but can disambiguate verbally ("the
        one on the second floor", "not the lab").
    """

    chosen_id: str | None = None
    free_text: str | None = None


class AmbiguousGoalError(Exception):
    """Raised by the resolver under strict (``raise_on_ambiguous=True``).

    Carries the :class:`ClarificationQuestion` so callers wrapping
    the resolver in a synchronous interface can pull the question
    off the exception without inspecting the result.
    """

    def __init__(self, question: ClarificationQuestion) -> None:
        super().__init__(question.question)
        self.question = question


# ``field`` is exported only to keep import statements stable across
# future additions to this module — frozen dataclasses don't need it
# today but linters that import the symbol shouldn't break tomorrow.
_ = field

__all__ = [
    "AmbiguousGoalError",
    "ClarificationAnswer",
    "ClarificationQuestion",
]
